  - name: install Percona repository
    template: src=templates/Percona.repo dest=/etc/yum.repos.d/Percona.repo
  - name: set permission
    action: file path=/etc/yum.repos.d/Percona.repo owner=root group=root

  - name: install signature file for Percona repository
    template: src=templates/RPM-GPG-KEY-percona dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-percona

  - name: set permission for signature file
    action: file path=/etc/pki/rpm-gpg/RPM-GPG-KEY-percona owner=root group=root

  - name: install sbtest.sh script
    template: src=templates/sbtest.sh dest=/usr/local/bin/sbtest.sh

  - name: set permission for sbtest.sh
    action: file path=/usr/local/bin/sbtest.sh owner=root group=root mode=0755

  - name: Install MySQL server and other packages
    yum: name={{ item }} state=present
    with_items:
      - Percona-Server-server-55
      - percona-toolkit
      - vim
      - telnet
      - git

  - name: ensure MySQL is running and starts on boot
    service: name=mysql state=started enabled=yes

#mysql-python doesn't work well with mysql-5.6 on os x
#  - name: Create Rain Gauge user with ALL privileges on ALL databases
#    mysql_user: name=raingauge host=localhost password={{ rg_password }} priv=PROCESS,SUPER:ALL state=present

  - name: Create MySQL sbtest database
    command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS `sbtest`"


